api:
    resource: "@ApiBundle/Controller/"
    type: rest
    prefix: /api

api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc

app:
    resource: "@AppBundle/Controller/"
    type: annotation

settings:
    resource: "@AppBundle/Controller/Settings"
    type: annotation
    prefix: /settings

public_access:
    resource: "@AppBundle/Controller/PublicAccess"
    type: annotation
    prefix: /public

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
